---
title: "Lectura conteos"
author: "Fernando Lucas Ruiz (fernando.lucas@um.es)"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    highlight: kate
    number_sections: true
    theme: spacelab
    toc: true
    toc_float: true
    code_folding: "hide"
  pdf_document:
    toc: true
subtitle: Cirugía digestiva, endocrina y trasplante de órganos abdominales (IMIB)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
```

```{r, message=FALSE}
source("Librerias.R")
source("utils.R")
```

# Conteos IonReporter

```{r}
# Directorio donde están los archivos Excel
directorio <- "../exportsR//"

# Listar todos los archivos que coinciden con el patrón
archivos <- list.files(path = directorio, pattern = ".*\\_consensus.txt$", full.names = TRUE)

todas_muestras <- data.frame()

# Leer y asignar cada archivo a una variable con el nombre correspondiente
for (archivo in archivos) {
  nombre_base <- sub("exports//", "", basename(archivo))
  nombre_base <- sub("\\_consensus.txt$", "", nombre_base)
  nombre_base <- sub("^.*?_", "", nombre_base)
  nombre_base <- sub("_[^_]*$", "", nombre_base)
  
  # Leer el archivo Excel
  datos <- read.delim(archivo)
  
  # seleccionar las columnas 
  datos <- dplyr::select(datos, c("Phylum", "Class", "Order", "Family", "Genus", "Species", "Count"))
  
  # Poner nombre de muestra
  datos <- mutate(datos, Sample = nombre_base)
  
  # ir añadiendo a un data.frame
  todas_muestras <- rbind(todas_muestras, datos)
  
}

# Aplicar trimws a todas las columnas de tipo carácter para quitar el espacio del principio
todas_muestras[] <- lapply(todas_muestras, function(x) if(is.character(x)) trimws(x, which = "left") else x)
```

```{r}
# Cambiar por ""
todas_muestras[] <- lapply(todas_muestras, function(x) if(is.character(x)) gsub("\\(family level ID only\\)", "", x) else x)

todas_muestras[] <- lapply(todas_muestras, function(x) if(is.character(x)) gsub("\\(slash calls\\)", "", x) else x)

todas_muestras[] <- lapply(todas_muestras, function(x) if(is.character(x)) gsub("\\(genus level ID only\\)", "", x) else x)

```

# Covariables

```{r}
covs <- read_excel("../CD anexo tesis.xlsx")

covs <- covs %>%
    dplyr::rename_with(~ gsub(" ", "_", .)) %>% # reemplaza espacios con guiones bajos
    dplyr::rename_with(~ gsub("[^[:alnum:]_]", "", .)) 

covs <- covs %>%
    dplyr::select(-AMSbiopharma_request,
                  -ID_ESTUDO,
                  - Nº_HISTOLÓGICO,
                  - DATA,
                  -DATA_NASCIMENTO
                  )

covs <- covs %>%
    dplyr::rename(`Sample` = Sample_description ,
                  `Pathology` = Pathology_group,
                  `Methyladenosine` = `1Methyladenosine`,
                  `X5methylTHF` = `5methylTHF`,
                  `X2aminooctanoic_acid` = `2aminooctanoic_acid`,
                  `X3phosphoglycerate` =`3phosphoglycerate`,
                  `X2isopropylmalic_acid` = `2isopropylmalic_acid`)
```

```{r}
covs$Sample <- gsub("-", "_", covs$Sample)
todas_muestras$codigo <- gsub("-", "_", todas_muestras$Sample)

cat("Presentes en covs \n")
setdiff(covs$Sample, todas_muestras$Sample)
cat("\n Presentes en lecturas \n")
setdiff(todas_muestras$Sample, covs$Sample)

```

```{r}
todas_muestras$Sample <- gsub("H13_11861", "H13_11681", todas_muestras$Sample)
todas_muestras$Sample <- gsub("H16_5568", "H16_05568", todas_muestras$Sample)
todas_muestras$Sample <- gsub("H15_3895", "H15_03895", todas_muestras$Sample)
todas_muestras$Sample <- gsub("H15_2920", "H15_02920", todas_muestras$Sample)
todas_muestras$Sample <- gsub("H13_7639", "H13_07639", todas_muestras$Sample)
todas_muestras$Sample <- gsub("H15_8368", "H15_08368", todas_muestras$Sample)
todas_muestras$Sample <- gsub("H13_2584", "H13_02584", todas_muestras$Sample)
todas_muestras$Sample <- gsub("H13_15361", "H12_15361", todas_muestras$Sample)
todas_muestras$Sample <- gsub("H10_8850", "H00_08850", todas_muestras$Sample)
todas_muestras$Sample <- gsub("H19_600", "H19_16005", todas_muestras$Sample)
todas_muestras$Sample <- gsub("H19_5699", "H19_05699", todas_muestras$Sample)
todas_muestras$Sample <- gsub("H18_8233", "H18_18233", todas_muestras$Sample)
todas_muestras$Sample <- gsub("H18_2561", "H18_12561", todas_muestras$Sample)

cat("Presentes en covs \n")
length(covs$Sample)
setdiff(covs$Sample, todas_muestras$Sample)
cat("\n Presentes en lecturas \n")
length(unique(todas_muestras$Sample))
setdiff(todas_muestras$Sample, covs$Sample)
```

```{r}
# covs <- covs %>%
#     dplyr::filter(!Sample %in% setdiff(covs$Sample, todas_muestras$codigo))
```

```{r, fig.width=20, fig.height=10}
vis_dat(covs)
```

```{r}
# covs %>% 
#     dplyr::select(where(is.character)) %>%
#     str
```

```{r}
covs$Pathology <- factor(covs$Pathology, levels = c("Sem alterações", "VHC", "HAI", "CBP"), labels = c("Healthy", "VHC", "HAI", "CBP"))
covs$GÉNERO <- factor(covs$GÉNERO)
covs$Leucocitos_totales <- as.numeric(covs$Leucocitos_totales)
covs$Linfocitos <- as.numeric(covs$Linfocitos)
```

```{r}
p1 <- ggplot(covs, aes(x = Sample, y = Linfocitos)) +
    geom_point()+
    facet_wrap(~Pathology, scales = "free")

p2 <- ggplot(covs, aes(x = Sample, y = Leucocitos_totales)) +
    geom_point()+
    facet_wrap(~Pathology, scales = "free")

gridExtra::grid.arrange(p1, p2, ncol = 2)
```

```{r}
covs <- covs %>%
    dplyr::select(-Leucocitos_totales, 
                  -Linfocitos,
                  -DIAGNÓSTICO_PRINCIPAL,
                  -Observações,
                  -DADOR_D__TRANSPLANTADO_T__NATIVO_N)
```

```{r, fig.width=20, fig.height=10}
vis_dat(covs) + theme(legend.text = element_text(size = 20))
```

```{r}
covs %>%
    dplyr::select(where(is.factor), Sample) %>%
    dplyr::filter(is.na(GÉNERO))
```

```{r}
covs <- covs %>%
    dplyr::mutate(across(where(is.numeric), ~ na_if(., 999)))
```

```{r, fig.width=20, fig.height=10}
vis_dat(covs) + theme(legend.text = element_text(size = 20))
```


```{r}
covs %>%
    dplyr::filter(Sample != "H16_05568") %>%
    dplyr::select(Sample, Pathology, where(~ any(is.na(.)) | !any(is.na(.))))
    # dplyr::select(INR:`Motivo do Transplante`)
```

```{r}
covs <- covs %>%
    dplyr::select(-A1_Final_mm2,
                  -A2_Inicial_mm2,
                  -Média_A1A2,
                  -GRANULOMAS_EPITELIÓIDES42,
                  -GRANULOMAS_EPITELIÓIDES43,
                  -PREDOMÍNIO_DE_TIPO_DE_CÉLULAS_INFLAMATÓRIAS49,
                  -SIDEROSIS,
                  -SIDEROSIS_TOPOGRAFIA,
                  -Sirolimus,
                  -Sirolimus_Conc_min,
                  -Everolimus,
                  -Everolimus_Conc_Mínima,
                  -Tacrolimus_Conc_Sangre,
                  -Ciclosporina_Conc_Sangre,
                  -antiVHC,
                  -RNAVHC,
                  -antiVHBs,
                  -antiVHBc,
                  -VHBsAg,
                  -VHBeAg,
                  -antiVHBe,
                  -DNA_VHB,
                  -antiVHA,
                  -INR,
                  -Tempo_de_Protrombina,
                  -Proteínas_Totais,
                  -Albumina,
                  -Bilirrubina_total,
                  -Bilirrubina_directa,
                  -Bilirrubina_indirecta,
                  -AST,
                  -ALT,
                  -GGT,
                  -FA,
                  -LDH,
                  -IgG,
                  -AMA,
                  -ANA,
                  -Ro52,
                  -LKM,
                  -Ac_AntiM2_ELISA,
                  -Ac_Anti_BPO_3E,
                  -Ac_Anti__gp210,
                  -Ac_AntiSp100,
                  -Ac_Anti_PML,
                  -ASMA,
                  -FActina,
                  -SLALP,
                  -Ac_AntiLC1,
                  -Ac_AntipANCA,
                  -Hemoglobina,
                  -Eritrocitos,
                  -Hematocrito,
                  -Neutrófilos,
                  -Eosinófilos,
                  -Monócitos,
                  -Tacrolimus,
                  -Ciclosporina,
                  -Micofenolato_de_Mofetilo_MMF,
                  -Corticóides,
                  -Azatioprina,
                  -UDCA,
                  -Quelantes,
                  -Diabetes,
                  -Diabetes_Tratada,
                  -HTA,
                  -HTA_Tratada,
                  -Dislipidemia,
                  -Dislipidemia_Tratada,
                  -Transplante_hepático_Nº,
                  -Motivo_do_Transplante
                  )

```

```{r, fig.width=20, fig.height=10}
vis_dat(covs) + theme(legend.text = element_text(size = 20))
```

```{r}
covs$LINFOCITOS_EM_EP <- factor(covs$LINFOCITOS_EM_EP, levels = c(0, 1), labels = c("ausente", "presente"))
covs$EOSINÓFILOS_EM_EP <- factor(covs$EOSINÓFILOS_EM_EP, levels = c(0, 1), labels = c("ausente", "presente"))
covs$NEUTRÓFILOS_EM_EP <- factor(covs$NEUTRÓFILOS_EM_EP, levels = c(0, 1), labels = c("ausente", "presente"))
covs$MACRÓFAGOS_EM_EP <- factor(covs$MACRÓFAGOS_EM_EP, levels = c(0, 1), labels = c("ausente", "presente"))
covs$PLASMÓCITOS_EM_EP <- factor(covs$PLASMÓCITOS_EM_EP, levels = c(0, 1), labels = c("ausente", "presente"))
covs$PREDOMÍNIO_DE_TIPO_DE_CÉLULAS_INFLAMATÓRIAS28 <- factor(covs$PREDOMÍNIO_DE_TIPO_DE_CÉLULAS_INFLAMATÓRIAS28, levels = c(0, 1, 2, 3, 4, 5, 6, 7, 8), labels = c("sin inflamación", "sin predominio", "linfocitos", "eosinófilos", "neutrófilos", "macrófagos", "plasmocitos", "granulocitos", "linfomonucleares"))
covs$MORFOLOGIA_NODULAR_DA_INFLAMAÇÃO<- factor(covs$MORFOLOGIA_NODULAR_DA_INFLAMAÇÃO, levels = c(0, 1), labels = c("ausente", "presente"))
covs$ZONALIZAÇÃO_DA_INFLAMAÇÃO_PORTAL <- factor(covs$ZONALIZAÇÃO_DA_INFLAMAÇÃO_PORTAL, levels = c(0, 1, 2, 3), labels = c("ausencia de zonalización", "periductal", "interfaz", "periductal e interfaz"))
covs$ACTIVIDADE <- factor(covs$ACTIVIDADE, levels = c(0, 1, 2, 3), labels = c("sin actividad", "ligera", "moderada", "severa"))
covs$FIBROSE <- factor(covs$FIBROSE, levels = c(0, 1, 2, 3, 4), labels = c("sin fibrosis", "fibrosis portal sin septos", "fibrosis portal con algunos septos", "fibrosis portal con numerosos septos","cirrosis"))
covs$REAÇÃO_DUCTULAR <- factor(covs$REAÇÃO_DUCTULAR, levels = c(0, 1), labels = c("ausente", "presente"))
covs$ENDOTELITE_CENTROVENULAR <- factor(covs$ENDOTELITE_CENTROVENULAR, levels = c(0, 1), labels = c("ausente", "presente"))
covs$TOPOGRAFIA_DA_INFLAMAÇÃO <- factor(covs$TOPOGRAFIA_DA_INFLAMAÇÃO, levels = c(0, 1, 2, 3), labels = c("ausencia de inflamación", "ausencia de predominio", "predominio portal", "predominio lobular"))
covs$NEUTRÓFILOS <- factor(covs$NEUTRÓFILOS, levels = c(0, 1), labels = c("ausente", "presente"))
covs$PLASMÓCITOS <- factor(covs$PLASMÓCITOS, levels = c(0, 1), labels = c("ausente", "presente"))
covs$TOPOGRAFIA_FIBROSE <- factor(covs$TOPOGRAFIA_FIBROSE , levels = c(0, 1, 2, 3, 4, 5, 6, 7), labels = c("sin fibrosis", "portal", "sinusoidal", "pericentrovenular", "portal y sinusoidal", "portal y sinusoidal", "portal y pericentrovenular", "sinusoidal y pericentrovenular"))
covs$COLESTASE <- factor(covs$COLESTASE , levels = c(0, 1, 2, 3), labels = c("ausencia", "portal", "intralobular", "portal e intralobular"))
covs$ESTEATOSIS_TIPO <- factor(covs$ESTEATOSIS_TIPO , levels = c(0, 1, 2, 3), labels = c("ausencia", "macrovesicular", "microvesicular", "mixto"))
covs$ESTEATOSIS_TOPOGRAFIA <- factor(covs$ESTEATOSIS_TOPOGRAFIA , levels = c(0, 1, 2, 3, 4), labels = c("ausencia", "Z1", "Z2", "Z3", "difuso"))
covs$EMPERIPOLESE <- factor(covs$EMPERIPOLESE, levels = c(0, 1), labels = c("ausente", "presente"))
covs$BALONIZAÇÃO_HEPATOCITARIA <- factor(covs$BALONIZAÇÃO_HEPATOCITARIA, levels = c(0, 1), labels = c("ausente", "presente"))
covs$CORPOS_HIALINOS_DE_MALLORY<- factor(covs$CORPOS_HIALINOS_DE_MALLORY, levels = c(0, 1), labels = c("ausente", "presente"))
covs$GLICOGENIZAÇÃO_NUCLEAR <- factor(covs$GLICOGENIZAÇÃO_NUCLEAR, levels = c(0, 1), labels = c("ausente", "presente"))
covs$LOBULITE<- factor(covs$LOBULITE, levels = c(0, 1), labels = c("ausente", "presente"))
covs$MACRÓFAGOS<- factor(covs$MACRÓFAGOS, levels = c(0, 1), labels = c("ausente", "presente"))
covs$LINFÓCITOS<- factor(covs$LINFÓCITOS, levels = c(0, 1), labels = c("ausente", "presente"))
covs$ENDOTELITE_PORTAL <- factor(covs$ENDOTELITE_PORTAL, levels = c(0, 1), labels = c("ausente", "presente"))

covs

```

```{r, fig.width=20, fig.height=10}
vis_dat(covs) + theme(legend.text = element_text(size = 20))
```

```{r}
covs %>%
    group_by(Pathology) %>%
    summarize(n = n()) %>%
    ggplot(aes(y=n, x = "", fill = Pathology)) +
    geom_bar(stat="identity", width=1, color="white") +
    scale_fill_manual(values = paletteer_d("ggsci::default_aaas")) +
    coord_polar("y", start=0) + 
    theme_void()

# Compute the position of labels
data <- covs %>%
    group_by(Pathology) %>%
    summarize(value = n())

data <- data %>% 
  arrange(desc(Pathology)) %>%
  mutate(prop = value / sum(data$value) *100) %>%
  mutate(ypos = cumsum(prop)- 0.5*prop )

# Basic piechart
ggplot(data, aes(x="", y=prop, fill=Pathology)) +
    geom_bar(stat="identity", width=1, color="white") +
    geom_text(aes(y = ypos, label = paste0(Pathology, "\n", value)), color = "white", size=6) +
    scale_fill_manual(values = paletteer_d("ggsci::default_aaas")) +
    coord_polar("y", start=0) +
    theme_void() + 
    theme(legend.position="none")
  
  
```


```{r, fig.width=15, fig.height=10}
data_long <- covs %>%
  dplyr::select(where(is.factor)) %>%
  pivot_longer(cols = -Pathology, 
               names_to = "Variable", values_to = "Value")

plots <- list()

for(variable in unique(data_long$Variable)) {
  
  data_filtered <- data_long %>%
    dplyr::filter(Variable == variable) %>%
    dplyr::group_by(Value, Pathology) %>%
    dplyr::summarize(Frequency = n(), .groups = 'drop') %>%
    mutate(Percentage = Frequency / sum(Frequency) * 100) %>%
    ungroup()
  
  p <- ggplot(data_filtered, aes(x = Pathology, y = Percentage, fill = Value)) +
    geom_col(position = "fill", alpha = 0.7) +
    scale_fill_viridis_d() +
    theme_minimal() +
    labs(title = variable,
         x = "", y = "Percentage") +
    theme(legend.position = "none") +
    theme(plot.title = element_text(size = 16), axis.title = element_text(size = 10)) +
    theme(axis.text.x = element_text(size = 16))+ 
    theme(legend.position = "top", legend.title = element_blank())
  
  plots[[variable]] <- p
}
length(plots)

do.call(grid.arrange, c(plots[1:8], ncol=4))
do.call(grid.arrange, c(plots[9:16], ncol=4))
do.call(grid.arrange, c(plots[17:24], ncol=4))
do.call(grid.arrange, c(plots[25:28], ncol=2))
```

```{r, fig.width=10, fig.height=10}

data <- covs %>%
    dplyr::select(Pathology, where(is.numeric))
plots <- list()

for(variable in names(data)) {
    if (variable == "Pathology"){
        next
    }
  p <- ggplot(data, aes_string(y = variable, x = "Pathology", fill = "Pathology")) +
    geom_boxplot(alpha=0.4) +
    geom_point(color = "#8B1A1A", size = 1, alpha = 0.7, position = position_jitter(width = 0.3, height = 0)) +
    scale_fill_viridis_d()+
    theme_minimal() +
    labs(title = variable,
         x = "", y = "Percentage") +
    theme(legend.position = "none") +
      stat_compare_means(label = "p.signif", vjust = 2, hjust= 2, ref.group = "Healthy") +
    theme(plot.title = element_text(size = 12), 
          axis.title = element_text(size = 10),
          axis.text.x = element_text(size = 16)) 
  
  plots[[variable]] <- p
}

do.call(grid.arrange, c(plots[1:9], ncol=3))
do.call(grid.arrange, c(plots[10:18], ncol=3))
do.call(grid.arrange, c(plots[19:27], ncol=3))
do.call(grid.arrange, c(plots[28:36], ncol=3))
do.call(grid.arrange, c(plots[37:45], ncol=3))
do.call(grid.arrange, c(plots[46:54], ncol=3))
do.call(grid.arrange, c(plots[55:62], ncol=3))
```

```{r}
covs <- covs %>%
    dplyr::select(-Nº_EP_SEM_DUCTO,
                  -Nº_EP_SEM_ARTERIOLA,
                  -Nº_EP_SEM_ARTERIOLA_E_SEM_DUCTO,
                  -EOSINÓFILOS
                  )
```


# Cargar TSE

## Preparar datos

### Colapsar taxonomia para random ids

```{r}
otus <- todas_muestras
taxonomia_combinada <- otus %>%
    unite("Combined", Phylum:Species, sep = "_", remove = F)

taxonos <- unique(taxonomia_combinada$Combined)
set.seed(123)  # Para reproducibilidad
random_ids <- replicate(length(taxonos), {
  first_letter <- sample(letters, 1)  # Seleccionar una letra para el primer carácter
  rest <- sample(c(letters, 0:9), 15, replace = TRUE)  # Generar el resto del ID
  paste(c(first_letter, rest), collapse = "")  # Combinar la letra con el resto
})

taxonos_ids <- data.frame(cbind(taxonos, random_ids))

# juntar taxonos_ids a todas_muestras 
otus <- dplyr::left_join(taxonomia_combinada, taxonos_ids, by = c("Combined" = "taxonos"))
```

```{r}
pretse <- prepare_TSE_data(otus, covs)
```

```{r}
pretse$abundance_table %>% as.data.frame()
pretse$tax
pretse$samples_metadata
```




```{r}
library(phyloseq)
# Asegúrate de que assay es una matriz
otu_table_data <- otu_table(pretse$abundance_table, taxa_are_rows = TRUE)

# Asegúrate de que rowData es un data.frame y conviértelo en una tax_table
tax_table_data <- tax_table(as.matrix(as.data.frame(pretse$tax)))

# Crea el objeto phyloseq
tse_phyloseq <- phyloseq(otu_table_data, tax_table_data)

sample_data(tse_phyloseq) <- sample_data(as.data.frame(pretse$samples_metadata))

library(tidyr)

# Convertir sample_data a data.frame, aplicar drop_na y reasignarlo
filtered_sample_data <- data.frame(sample_data(tse_phyloseq)) %>%
    drop_na(Batch, Supervivencia)

# Reasignar el sample_data filtrado al objeto phyloseq
sample_data(tse_phyloseq) <- sample_data(filtered_sample_data)

```

```{r, fig.width=20, fig.height=20, warning=FALSE}
dist_methods <- unlist(distanceMethodList)
# Remove them from the vector
dist_methods <- dist_methods[-(1:3)]

# Remove the user-defined distance
dist_methods = dist_methods[-which(dist_methods=="ANY")]

plist <- vector("list", length(dist_methods))
names(plist) = dist_methods
failed_methods <- c()  # Lista para almacenar los métodos que fallan

for (i in dist_methods) {
    # Intenta calcular la matriz de distancia y la ordenación con manejo de errores
    tryCatch({
        # Calcula la matriz de distancia
        iDist <- distance(tse_phyloseq, method = i)
        
        # Calcula la ordenación (cambia "MDS" a "PCoA" si es necesario)
        iMDS <- ordinate(tse_phyloseq, "MDS", distance = iDist)
        
        # Crear el gráfico si la ordenación es exitosa
        p <- plot_ordination(tse_phyloseq, iMDS, color = "Batch", shape = "Supervivencia") +
             ggtitle(paste("MDS using distance method", i))
        
        # Guardar el gráfico en la lista
        plist[[i]] <- p
    }, error = function(e) {
        # Si ocurre un error, añade el método a la lista de fallos
        failed_methods <<- c(failed_methods, i)
        # message(paste("Failed for distance method:", i))
    })
}


df = plyr::ldply(plist, function(x) x$data)
names(df)[1] <- "distance"
p = ggplot(df, aes(Axis.1, Axis.2, color=Batch, shape=Supervivencia))
p = p + geom_point(size=3, alpha=0.5)
p = p + facet_wrap(~distance, scales="free")
p = p + ggtitle("MDS on various distance metrics for Enterotype dataset")
p
```

Para chequear que todos esta correcto

```{r}
taxa_corrected_salida <- data.frame(t(taxa_corrected_salida$tax_final))
# Quitar la "X" solo de los nombres de columnas que empiezan por "X"
colnames(taxa_corrected_salida) <- sub("^X", "", colnames(taxa_corrected_salida))

rownames(taxa_corrected_salida) <- sub("^X", "", rownames(taxa_corrected_salida))

pretse$abundance_table <- as.matrix(taxa_corrected_salida)

```

## Profundidad de muestreo

```{r}
# Extraer la matriz de abundancias del objeto TSE
abundances <- data.frame(t(pretse$abundance_table))

# Calcular la profundidad mínima
abundances$sample <- rownames(abundances)

abundances_long <- pivot_longer(
  abundances, 
  cols = -sample,  # Especificamos que las columnas de especies deben ser pivotadas
  names_to = "Taxa",           # La nueva columna que contendrá los nombres de las especies
  values_to = "Abundance"        # La nueva columna que contendrá los valores de abundancia
)

abundances_long %>% 
    dplyr::group_by(sample) %>%
    dplyr::summarize(n_seqs = sum(Abundance)) %>%
    ggplot(aes(x = n_seqs)) +
    geom_histogram(bins= 100)

abundances_long %>% 
    dplyr::group_by(sample) %>%
    dplyr::summarize(n_seqs = sum(Abundance),
              n_sings = sum(Abundance == 1),
              goods = 100*(1 - n_sings / n_seqs)) %>%
    ggplot(aes(x=n_seqs, y = goods)) +
    geom_point()


min_n_seqs <- abundances_long %>% 
    dplyr::group_by(sample) %>%
    dplyr::summarize(n_seqs = sum(Abundance),
              min = min(n_seqs)) %>%
    pull(min)

quantil1_n_seqs <- abundances_long %>% 
    dplyr::group_by(sample) %>%
    dplyr::summarize(n_seqs = sum(Abundance)) %>%
    pull(n_seqs) %>%            
    quantile(probs = 0.25)

abundances <- abundances %>% 
    dplyr::select(-sample)

# Crear curva de rarefacción con los datos originales
rarecurve_data <- rarecurve(abundances, step=100, col="blue", label=T, cex=0.6)
map_dfr(rarecurve_data, bind_rows) %>%
   bind_cols(sample = rownames(abundances),.) %>%
    pivot_longer(-sample) %>%
    drop_na() %>%
    mutate(n_seqs = as.numeric(str_replace(name, "N", ""))) %>%
    select(-name)%>%
    ggplot(aes(x = n_seqs, y = value, group = sample)) +
    geom_vline(xintercept = quantil1_n_seqs, color = "grey", shape = "dashed") +
    geom_line() +
    theme_minimal()+
    labs(x= "number of species", y = "counts", title = "LP")

# Aplicar rarefacción real a las abundancias
rarefied_abundances_LP <- rrarefy(abundances, sample=quantil1_n_seqs)

# (Opcional) Crear curva de rarefacción con los datos rarefactados
rarecurve_rarefied_data <- rarecurve(rarefied_abundances_LP, step=100, col="blue", label=T, cex=0.6)
map_dfr(rarecurve_rarefied_data, bind_rows) %>%
    bind_cols(sample = rownames(abundances),.) %>%
    pivot_longer(-sample) %>%
    drop_na() %>%
    mutate(n_seqs = as.numeric(str_replace(name, "N", ""))) %>%
    select(-name)%>%
    ggplot(aes(x = n_seqs, y = value, group = sample)) +
    geom_vline(xintercept = quantil1_n_seqs, color = "grey", shape = "dashed") +
    geom_line() +
    theme_minimal()+
    labs(x= "number of species", y = "counts", title = "LP")

pretse$abundance_table <- t(rarefied_abundances_LP)
```

